version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    container_name: mbsapp
    depends_on:
      - mbsdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mbsdb:5432/multiplex
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Nikki6499@
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  mbsdb:
    image: postgres:14.1-alpine
    restart: always
    container_name: mbsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nikki6499@
      - POSTGRES_DB=multiplex
    ports:
      - "5432:5432"